version: '3.8'

services:
  motion-live-photo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - CORS_ORIGIN=*
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    container_name: motion-live-photo-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads: